### ISSUE TITLE
Amiga Transformer generates a Guru

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#409]
Emulator Disk Transformer v1.21 - A-Max - Go-64! V2.0 - BBC (1988)(-)(De).adf

To reproduce, select 1 from the start menu…

<img width="900" alt="Bildschirmfoto 2020-09-16 um 20 28 02" src="https://user-images.githubusercontent.com/12561945/93377646-9690b600-f85b-11ea-9840-3ef8716d3890.png">

UAE: 👍

<img width="722" alt="Bildschirmfoto 2020-09-16 um 20 27 27" src="https://user-images.githubusercontent.com/12561945/93377675-a0b2b480-f85b-11ea-9049-5b7967fe883e.png">

vAmiga: 🙈

<img width="900" alt="Bildschirmfoto 2020-09-16 um 20 27 44" src="https://user-images.githubusercontent.com/12561945/93377687-a60fff00-f85b-11ea-8be9-3a43eecc2349.png">

BTW, C64 emulation works fine in vAmiga 🤤

<img width="900" alt="Bildschirmfoto 2020-09-16 um 20 29 33" src="https://user-images.githubusercontent.com/12561945/93377701-ad370d00-f85b-11ea-93eb-820e6d70ccb7.png">

<img width="900" alt="Bildschirmfoto 2020-09-16 um 20 29 39" src="https://user-images.githubusercontent.com/12561945/93377713-af00d080-f85b-11ea-9669-0b7ada72711f.png">

**Comment by dirkwhoffmann** [comment]
To ease debugging, here is an isolated test case that boots into transformer right away: 

[at.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/5236693/at.adf.zip)

It boots fine in SAE (kick1.3, ECS Agnus, 512 + 512) with lowest compatibility settings (Immediate Blitter, Turbo drive)

<img width="722" alt="Bildschirmfoto 2020-09-17 um 08 05 53" src="https://user-images.githubusercontent.com/12561945/93427157-a5a85000-f8bd-11ea-85d6-cac611bc8a9e.png">

**Comment by dirkwhoffmann** [comment]
The Guru issue turned out to be an easy one. After setting up, the CPU performs a soft reset (RESET instruction) which didn't work as expected in vAmiga. This has been fixed: 

<img width="900" alt="Bildschirmfoto 2020-09-17 um 14 33 25" src="https://user-images.githubusercontent.com/12561945/93471527-bf648a00-f8f3-11ea-913d-3a5496252f3e.png">

Now, the question is: What is a DOS diskette? A diskette with MSDOS on it? Or a blank disk in DOS format? Maybe we should try to get a manual for this tool...

I tried with a blank DOS disk in UAE, but it ended up in a Guru 😯.

Does anybody have a DOS diskette with MSDOS in ADF format?

**Comment by mithrendal** [comment]
I still have the original disk of this piece of software... The Commodore Amiga labeled transformer disk  came with my Amiga1000. if I remember correctly you had to insert a original 720KB MS-DOS disk into it. PC formatted. For example MSDOS 3.3. I remember that I used it in 1989/90 or so to play around with pascal and it worked albeit very slowly ...  I did not like pascal then... because I already mastered C and has become used to it ...

**Comment by dirkwhoffmann** [comment]
![image](https://user-images.githubusercontent.com/12561945/93491658-3e64bd00-f90a-11ea-8333-c43b6eddf9b9.jpeg)

> 720KB MS-DOS disk into it. PC formatted 720 KB was crucial. For example MSDOS 3.3.

Yes, exactly. Now, we need that disk in ADF format 🤤.

Once we've got that disk, we install windows. And once we've got Windows running, we install Microsoft Flight Simulator 2020. 🙊

**Comment by mithrendal** [comment]
Hmm I looked in my old disk box ... and found this ...


![grafik](https://user-images.githubusercontent.com/17108995/93500262-63f6c400-f914-11ea-9c1c-58f8b4db7ab4.png)

I think it is the mentioned MSDOS3.3 Pascal disk ...

What if we try to load it from the Amiga1000 with the serial connection and the AmigaExplorer program ... it could be that we will get as a result an ADF with that disk no ? Is it then still PCFormatted ?

**Comment by dirkwhoffmann** [comment]
> What if we try to load it from the Amiga1000 with the serial connection and the AmigaExplorer program ...

This could work if AmigaExplorer is able to create ADF files for disks in PC format. They are just like standard ADFs with less sectors per track (9 instead of 11). This is also how they can be recognized. They have a slightly smaller file size.

**Comment by dirkwhoffmann** [comment]
> Is it then still PCFormatted ?

AmigaExplorer runs on Windows, right? UAE is able to create blank ADFs in PC format (I did this an hour ago). Maybe AmigaExplorer can be told to write into this (blank) ADF.

**Comment by tonioni** [comment]
PC floppy can't exist in ADF format. Either you need to support PC floppy disk images (*.ima usually) in emulator (convert to PC MFM format) or support for example extended ADF that can handle any raw MFM image.

**Comment by dirkwhoffmann** [comment]
> Either you need to support PC floppy disk images (*.ima usually)

I "found" MSDOS3.3.img,  renamed it to MSDOS.IMA and mounted it in df1:. I guess, IMA and IMG are the same, because it booted without any issue in UAE:

<img width="720" alt="Bildschirmfoto 2020-09-18 um 22 49 36" src="https://user-images.githubusercontent.com/12561945/93644121-a1854b00-fa01-11ea-9476-90da7452a10d.png">

Very nice!

Fun fact: MSDOS 3.3 refuses the current date. It interprets it as 1920, I guess 😳.

**Comment by dirkwhoffmann** [comment]
> Either you need to support PC floppy disk images (*.ima usually) in emulator (convert to PC MFM format)...

That's the way to way to go 😎. Let’s see what the new version can do… 

To that point, I had it already working:

<img width="787" alt="Bildschirmfoto 2020-09-20 um 14 32 04" src="https://user-images.githubusercontent.com/12561945/93711745-0a2f0d80-fb51-11ea-8e41-5f7d8dfdf52b.png">

Now, let’s drag in a MSDOS 3.3 boot disk…

<img width="787" alt="Bildschirmfoto 2020-09-20 um 14 33 42" src="https://user-images.githubusercontent.com/12561945/93711750-0e5b2b00-fb51-11ea-9e1f-641677a00ce3.png">

… and insert that puppy into df1. 

<img width="787" alt="Bildschirmfoto 2020-09-20 um 14 54 51" src="https://user-images.githubusercontent.com/12561945/93711819-97726200-fb51-11ea-911a-22e9ced84059.png">

Tension rising… I better close my eyes 🙈

Woohoo. MSDOS in action 😃.

<img width="899" alt="Bildschirmfoto 2020-09-20 um 14 23 43" src="https://user-images.githubusercontent.com/12561945/93711820-9fca9d00-fb51-11ea-9ec4-6afedc47305e.png">
<img width="899" alt="Bildschirmfoto 2020-09-20 um 14 24 14" src="https://user-images.githubusercontent.com/12561945/93711825-a6f1ab00-fb51-11ea-9f8e-820d38fbb892.png">

With Amiga Transforming working, we can switch to ARM based Macs without hesitation. If Apple decides to cancel PC support, we still have Amiga Transformer. The PC is a „Tool for Modern Times“, see:

![unnamed](https://user-images.githubusercontent.com/12561945/93711830-af49e600-fb51-11ea-986e-1e406d28c553.jpg)

In warp mode, Amiga Transformer is even faster than the original PC. 😎 

Unfortunately, it’s not 100% bug free, yet 🙄. It only works if AmigaTransfomer is inserted in df0: before the Amiga is powered up. If it is inserted after the hand & disk logo has shown up, it produces a Guru when booting from the PC disk. This is likely due to the implementation of the RST instruction. It’s still unclear to me which components are reset and which are not when the CPU triggers a reset. 

Furthermore, some important features are missing, namely:

- A DOS disk *de*coder in order to save disks back to .img files.
- Support for 5.25“ PC disks. At the moment, the emulator only accepts 3.5“ DD disks (either .img or .ima which I have assumed to be the same).

**Comment by mithrendal** [comment]
@dirk Is there any chance to get my TurboPascal DOS disk into an ima file ? ... The only computer I have, which has a floppy is the Amiga1000 😬...  

![grafik](https://user-images.githubusercontent.com/17108995/93756487-7c612a00-fc05-11ea-9436-e92396719d9d.png)

I will once again unearth the Amiga1000 tonight ... this reminds me somehow of mark twainy story of huckleberry finn and tom saywer at the graveyard and the cat 🙀 which I read when I was a child ... ouch that was really scaring 💀 ... Maybe AmigaExplorer can make an .ima file ?

**Comment by dirkwhoffmann** [comment]
> Is there any chance to get my TurboPascal DOS disk into an ima file ?

Don't know. I haven't been successful with my latest attempts to read or write (virtual) PC disks on the Amiga in UAE. I tried to install the CrossDos drivers as it is described here: 

https://www.mingos-commodorepage.com/tutorials/amigapctoamigacrossdos.php

But there is no PC1: icon showing up, no matter which disk I try.

I've also tried to boot from some 5.25" MS DOS images with Amiga Transformer (with df1: configured as a 5.25" drive in UAE), but it always produced a Guru. I think the 3.5" Dell MS DOS 3.3 disk which I used in my experiments above is one of the rare versions that are compatible with Amiga Transformer.

**Comment by dirkwhoffmann** [comment]
Strange. My new code basically resets everything except the internal CPU state and memory if the CPU executes the RESET instruction. But after hitting RETURN, Amiga Transformers still produces the Guru if the Transformer disk was inserted after the hand & disk logo has shown up (it still works if the disk is present on power up). This means that Amiga Transformer must stumble across some unexpected memory contents that has been created on power up if no disk was present.

**Comment by mithrendal** [comment]
Have you tried to give it only 512kb chipram? Because that piece of software is from 1985 or so. Maybe they had not tested it on a fastram machine ...

**Comment by dirkwhoffmann** [comment]
> Have you tried to give it only 512kb chipram?

With 512 Chip  + 0 Slow, it works, no matter when I insert the disk. However, in UAE it also works with 512 Chip + 512 Slow. 

This might be related to the Jetsons bug that only occurs if SlowRam is added. But what on earth could go wrong with Slow Ram during the boot process? 🤔

**Comment by mithrendal** [comment]
...inserted the TurboPascal DOS-disk into the A1000 in df0: and now we are here

![grafik](https://user-images.githubusercontent.com/17108995/93810805-74c67300-fc4f-11ea-87e6-eaeb95377887.png)


lets try to pull it over the serial link ...

![grafik](https://user-images.githubusercontent.com/17108995/93811066-e1da0880-fc4f-11ea-817e-e69747cef60e.png)

uh that does not look good ... either AmigaExplorer can does support to copy DOS formatted disks or the disk is already bad after all these years ... I have to try to boot it into AmigaTransformer on the A1000 hang on ...

**Comment by mithrendal** [comment]
![A81A52E8-4ADD-48C5-A801-B9FA000E16D2](https://user-images.githubusercontent.com/17108995/93812744-544be800-fc52-11ea-905e-ef92297f63fb.jpeg)

Ready to rumble A1000 in PC mode. 😎

![83134615-B833-4149-944D-97CA767BCAEA](https://user-images.githubusercontent.com/17108995/93812857-780f2e00-fc52-11ea-88ee-b6192ad085ab.jpeg)


😭oh no disk error

**Comment by mithrendal** [comment]
First try I booted from your at.adf that did not work...

Now I tried my own AmigaTranformer and that worked

![FB342ADF-0124-4F9D-A1FF-A1FCB40A3F23](https://user-images.githubusercontent.com/17108995/93814864-6e3afa00-fc55-11ea-87eb-b5953172f561.jpeg)

![E7E3EDC0-E1E0-421A-8EE7-8541AF58DF61](https://user-images.githubusercontent.com/17108995/93814921-83b02400-fc55-11ea-8d18-cde1f0a59f48.jpeg)

**Comment by mithrendal** [comment]
I again looked a the screenshots from yesterdays graveyard session ... 

yours at.adf expects boot disk in df1: 
my AmigaTransformer expects msdos bootdisk  in df0: 

thats why I got read errors ... why does the software not print out a "drive not present error" ?🙄

Ok ... so we know now ancient disks are still fine ... but AmigaExplorer can not transfer those dos formatted disks ... as toni already told us before  😌

**Comment by dirkwhoffmann** [comment]
> my AmigaTransformer expects msdos bootdisk in df0:

Uh, you've  got a "single drive" transformer. I didn't notice that. 😮

> Ok ... so we know now ancient disks are still fine

Fascinating, but we've already learned that from Battlestar Galactica. The old ship was the most reliable.

> but AmigaExplorer can not transfer those dos formatted disks ... as toni already told us before

Damn, he's always right. 😉
