### ISSUE TITLE
Xbox One Controller (wired): using Hat Switch instead of left Switch

### ISSUE THREAD

**Issue by warpdesign** [dirkwhoffmann/vAmiga#495]
I am using an Xbox One wired controller: it works perfectly.

Only problem is that up/down/left/right only work when using the Left stick: Is there a way to make the Hat Switch act as left/right/up/down?

**Comment by dirkwhoffmann** [comment]
Could you post a screenshot such as this one? 

<img width="758" alt="Bildschirmfoto 2021-05-05 um 18 31 23" src="https://user-images.githubusercontent.com/12561945/117176458-35a8f480-add0-11eb-9396-a258c06f40b3.png">

I do have a wireless Xbox controller, but not a wired one.

**Comment by warpdesign** [comment]
Sure:

![image](https://user-images.githubusercontent.com/199648/117189023-fed9db00-addd-11eb-84b4-9a03bc7de970.png)

I also noticed that pressing any of the hat direction will actually trigger fire in the Amiga emulator: not sure why.

**Comment by dirkwhoffmann** [comment]
> I also noticed that pressing any of the hat direction will actually trigger fire in the Amiga emulator: 

This means the hat switch buttons are recognized as they were real buttons. Strange.

**Comment by warpdesign** [comment]
The controller also works correctly in the few games I tried it on like OpenEmu.

**Comment by dirkwhoffmann** [comment]
Could you post an Amazon link to the exact controller you have? I'd like to add the controller to the list of yet unsupported devices.

**Comment by warpdesign** [comment]
I guess this is this one (I bought it a long time ago :)): https://www.amazon.com/Xbox-Wireless-Controller-White-one/dp/B01GW3H3U8

It's wireless, but I only use it plugged as USB on the Mac.

Note that I had to install some kind of driver to make it work: https://github.com/360Controller/360Controller/releases

Here is the mapping panel of this driver if that helps (this is the default mapping, I never touched it):
![image](https://user-images.githubusercontent.com/199648/117259310-32ece480-ae4e-11eb-8dde-77a28253ace4.png)

(it's written "Xbox 360 Wired Controller" but this is an Xbox One controller)

**Comment by dirkwhoffmann** [comment]
I might have the exact same controller in my possession:

![IMG_0945](https://user-images.githubusercontent.com/12561945/117261609-a3950080-ae50-11eb-9aee-087c31f68b64.JPG)

Unfortunately, the driver does not work with Big Sur, so I don't know if can do anything about it.

According to the screenshot of the mapping panel, it appears to me that the hat switch is mapped to buttons 0 to 3. Does the tool  allow you to map the hat switch to real joystick movements?

**Comment by warpdesign** [comment]
> Unfortunately, the driver does not work with Big Sur, so I don't know if can do anything about it.
I am using Big Sur. I guess it works for me because I installed it before updating to Big Sur.

**Comment by warpdesign** [comment]
> Does the tool allow you to map the hat switch to real joystick movements?

Unfortunately I can only change which "input" will a button of the controller trigger, but not the other way around.

When clicking on "Start Remapping", it hightlights a button on the image, I press it, and it binds it to a specific input number. And so on for each button.

**Comment by dirkwhoffmann** [comment]
I've searched some drawers in the basement and found a 17" MacBook Pro from 2009 running El Capitan (unbelievable how good looking macOS was ten years ago 😍). On that machine, the driver works like a charm. 

I run https://gamepad-tester.com with the following results:

<img width="874" alt="Bildschirmfoto 2021-05-07 um 08 30 18" src="https://user-images.githubusercontent.com/12561945/117407499-ee754d80-af0e-11eb-803b-49638dd1e60c.png">

- Hatswitch Up: B11
- Hatswitch Down: B12
- Hatswitch Left: B13
- Hatswitch Right: B14

I've also checked the Xbox buttons A,B,X,Y:

- Y: B3
- X: B2
- A: B0
- B: B1

I'll try to add an option that makes vAmiga translate buttons to directional events. This might be useful for other controllers as well.

**Comment by warpdesign** [comment]
Thank you!

I am not fond of recent macOS designs, especially Big Sur.

**Comment by dirkwhoffmann** [comment]
Could you give this experimental build a try? 

[vAmiga.zip](https://github.com/dirkwhoffmann/vAmiga/files/6440158/vAmiga.zip)

It should recognise the controller and display the following settings:

<img width="582" alt="Bildschirmfoto 2021-05-07 um 10 21 07" src="https://user-images.githubusercontent.com/12561945/117421788-25535f80-af1f-11eb-9f32-3b57a6048589.png">

Could you check the right analog joystick, too? I am using the same scheme as for the Xbox Carbon Black which might be right or wrong.

**Comment by warpdesign** [comment]
Here is what I see with this build:

![image](https://user-images.githubusercontent.com/199648/117434640-373bff00-af2d-11eb-8aa7-3e02b3a44e0a.png)

Pressing hat directions seem to trigger wrong buttons:

- pressing left goes right
- pressing up goes down
- pressing down goes left
- pressing right does nothing

Also, using the right stick does nothing.

**Comment by dirkwhoffmann** [comment]
> pressing left goes right

I see. I did some experiments with the Sony DualShock which uses this mapping:

<img width="481" alt="Bildschirmfoto 2021-05-07 um 14 14 19" src="https://user-images.githubusercontent.com/12561945/117448289-d9181780-af3e-11eb-99e5-b88eaa085fec.png">

b0 delivers a `usage` value of 1, b1 a `usage` value of 2 and so on. This means the HID library starts counting buttons with 1, not 0, which is the reason for the shift.

**Comment by dirkwhoffmann** [comment]
Here is another build:

[vAmiga.zip](https://github.com/dirkwhoffmann/vAmiga/files/6442083/vAmiga.zip)

 I've reworked and renamed the mapping schemes. For the Xbox wired controller, the correct hat switch scheme is B11 - B14.

If the emulator crashes again, please repost the crash log. The old log doesn't tell us anything, because it was created from a release build. The new build is a debug build.

**Comment by dirkwhoffmann** [comment]
Should be fixed in v1.0r3. Please reopen if not.

**Comment by warpdesign** [comment]
@dirkwhoffmann Unfortunately the mapping still isn't correct I'm afraid.

Tried both the zip from your previous post & the latest v1.0r3 and both give these results:

- pressing up: OK
- pressing Down: pulls Right instead
- pressing Left: pulls Down instead
- pressing Right: pulls Left instead
