### ISSUE TITLE
RSI Sarcophaser Crack

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#534]
Gfx garbage under the logo at the top.

![vamiga](https://user-images.githubusercontent.com/3858768/133300961-9ec34dfc-9791-4956-bb2a-af8685d9f033.png)
![winuae](https://user-images.githubusercontent.com/3858768/133300966-8742df65-b43b-422f-b3b5-5769b256725a.png)
[RSI-CrackSarcophaser.zip](https://github.com/dirkwhoffmann/vAmiga/files/7163780/RSI-CrackSarcophaser.zip)

**Comment by dirkwhoffmann** [comment]
Works with the latest code changes (likely a duplicate of #522)

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2

**Comment by chris70c** [comment]
This one still doesn't work for me, #522 is indeed fixed but this one looks the same as before (with the garbage behind the logo) in latest 1.1b2.

**Comment by dirkwhoffmann** [comment]
This might be an OCS/ECS issue. In the desktop version, it works fine if an ECS Agnus is selected. With OCS Agnus, it looks like this:

<img width="853" alt="Bildschirmfoto 2021-09-17 um 17 52 13" src="https://user-images.githubusercontent.com/12561945/133827178-32f02eaf-98e3-4bc3-bee5-a14c9c250198.png">

In SAE, it runs fine with an OCS Agnus, too, but this might be due to the initial memory pattern. @mithrendal is a lucky owner of a real A1000. Maybe he could give this demo a try on his machine.

All my original machines are A500s with Kickstart 1.3. These machines are already equipped with an ECS Agnus. My original Amiga 500 from back in the day had Kickstart 1.2. It was equipped with the older OCS chip, but this machine didn't make it. My parents gave it away many years ago.

**Comment by chris70c** [comment]
I'm 100% sure this should work correctly with OCS, I remember this demo quite well, is very old and was used for a game called Sarcophaser which is from 1988 so there was no ECS in any Amiga machine at that time. It does works correctly on WinUAE with OCS 512K+512K and KS1.3.

**Comment by dirkwhoffmann** [comment]
> I'm 100% sure

OK, 100% is a convincing number. I'll look into it... @mithrendal: No need to wake up the A1000 from hypersleep yet.

**Comment by dirkwhoffmann** [comment]
Actually, it turned out to be easy. Remember the suspicious code that was responsible for dropping write accesses to bitplane pointer registers? Yes, the code for which I didn't remember why it was there. It turned out that I only removed that code from `setBPLxPTL`. It was still active on `setBPLxPTH` which caused the bug.

I still don't remember why this code came in. More and more, it reminds me of this:
https://en.battlestarwikiclone.org/wiki/Cylon_transponder
